title: My Website
author: Tusharr Gupta
email: guptatushar080202@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Tushar Gupta's Portfolio

# social links
twitter_username: callmetushh # DO NOT include the @ character, or else the build will fail!
github_username:  Tusharr08 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
